### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by yourmom-jpeg** [TheRatCode/RatPoison#667]
**Describe the bug**
I tried running the cheat, following the instructions, and got these errors shown in the picture

**To Reproduce**
Launch CGSO and run it. Even in Admin mod I got the error

**Pictures/Videos**
![Capture](https://user-images.githubusercontent.com/59025428/101271359-f0649600-374f-11eb-874f-0c8dff8a1c84.JPG)

**Comment by yourmom-jpeg** [comment]
I also tried the beta to no avail

**Comment by sotakoira** [comment]
Make sure your GPU drivers are fully up-to-date.
Make sure `java.exe` process is running on dedicated (more powerful) GPU.
Try switching` \build\RatPoison 1.x\settings\OpenGL.txt` variable `OPENGL_3 = true` to <code>false</code>.
If problem persists **it's a result of outdated hardware** unable to run overlay properly. You can run the cheat with `MENU = false` in 
` \build\RatPoison 1.x\settings\General.txt` but you would have to configure the cheat by editing files and you wouldn't be able to use overlay features at all.

**Comment by yourmom-jpeg** [comment]
If it helps I have a horribly underpowered GPU (AMD HD5830). Maybe that's the issue

**Comment by yourmom-jpeg** [comment]
Also I'd like to know how to make Java run on my GPU

**Comment by sotakoira** [comment]
`The Radeon HD 5830 was a graphics card by ATI, launched in February 2010.`
Sounds like the reason of your problem. Have fun playing without menu I guess.

> 
> 
> Also I'd like to know how to make Java run on my GPU

Some laptop users have this problem due to Intel GPU being forced on the process instead of the dedicated Nvidia GPU. 
In Intel/Nvidia case: right click on the desktop, select `NVIDIA Control Panel`, go to `Manage 3D settings` -> `Program settings` -> `Add` -> `OpenJDK Platform binary` -> `Select the preferred graphics processor for this program` -> `High-performance NVIDIA processor` then click on `Apply `button.

**Comment by yourmom-jpeg** [comment]
Well that's unfortunate. Guess I'll have to upgrade before I use RatPoison. Just wondering, will an R9 Fury work for this? Closing now

**Comment by sotakoira** [comment]
If somebody ever stumbles upon this thread, feel free to read [this](https://github.com/libgdx/libgdx/issues/3559) issue on libgdx repo, possibly hinting this is affecting specific hardware.
